# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'shareManagerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for shareManagerDemo

  pod 'UMCCommon'
  pod 'UMCSecurityPlugins'
  pod 'UMCCommonLog'

  #U-Share SDK UI模块（分享面板，建议添加）
  pod 'UMCShare/UI'

  #集成微信(精简版0.2M)
  pod 'UMCShare/Social/ReducedWeChat'
  #集成QQ/QZone/TIM(精简版0.5M)
  pod 'UMCShare/Social/ReducedQQ'
  #集成新浪微博(精简版1M)
  pod 'UMCShare/Social/ReducedSina'

end
